export enum EFormatLang {
	AF = 'Afrikaans',
	AL = 'Albanian',
	AR = 'Arabic',
	AZ = 'Azerbaijani',
	BG = 'Bulgarian',
	CA = 'Catalan',
	CZ = 'Czech',
	DA = 'Danish',
	DE = 'German',
	EL = 'Greek',
	EN = 'English',
	EU = 'Basque',
	FA = 'Persian (Farsi)',
	FI = 'Finnish',
	FR = 'French',
	GL = 'Galician',
	HE = 'Hebrew',
	HI = 'Hindi',
	HR = 'Croatian',
	HU = 'Hungarian',
	ID = 'Indonesian',
	IT = 'Italian',
	JA = 'Japanese',
	KR = 'Korean',
	LA = 'Latvian',
	LT = 'Lithuanian',
	MK = 'Macedonian',
	NO = 'Norwegian',
	NL = 'Dutch',
	PL = 'Polish',
	PT = 'Portuguese',
	PT_BR = 'Português Brasil',
	RO = 'Romanian',
	RU = 'Russian',
	SV = 'Swedish',
	SE = 'Swedish',
	SK = 'Slovak',
	SL = 'Slovenian',
	SP = 'Spanish',
	ES = 'Spanish',
	SR = 'Serbian',
	TH = 'Thai',
	TR = 'Turkish',
	UA = 'Ukrainian',
	UK = 'Ukrainian',
	VI = 'Vietnamese',
	ZH_CN = 'Chinese Simplified',
	ZH_TW = 'Chinese Traditional',
	ZU = 'Zulu',
}

export enum EFormatUnits {
	METRIC = 'metric',
	STANDART = 'standart',
	IMPERIAL = 'imperial',
}

export enum EFormatMode {
	XML = 'xml',
	HTML = 'html',
	JSON = 'json',
}
